#!/usr/bin/env bash

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Startup programs
hyprpaper &
waybar &

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# App Binds
riverctl map normal Super T spawn foot
riverctl map normal Super B spawn firefox
riverctl map normal Super R spawn "wofi --show drun"
riverctl map normal Super F spawn nautilus 
riverctl map normal Super W spawn "pkill waybar || waybar"
riverctl map normal Super+Shift S spawn "hyprshot -m region"

# Window Manipulation
riverctl map normal Super C close
riverctl map normal Super F toggle-fullscreen

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super Left focus-view left
riverctl map normal Super Right focus-view right
riverctl map normal Super Up focus-view up
riverctl map normal Super Down focus-view down

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift Left swap left
riverctl map normal Super+Shift Right swap right
riverctl map normal Super+Shift Up swap up
riverctl map normal Super+Shift Down swap down

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Control Left send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control Right send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
# riverctl map normal Super+Alt H move left 100
# riverctl map normal Super+Alt J move down 100
# riverctl map normal Super+Alt K move up 100
# riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal Super+Alt+Control H snap left
# riverctl map normal Super+Alt+Control J snap down
# riverctl map normal Super+Alt+Control K snap up
# riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
# riverctl map normal Super+Alt+Shift H resize horizontal -100
# riverctl map normal Super+Alt+Shift J resize vertical 100
# riverctl map normal Super+Alt+Shift K resize vertical -100
# riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    # riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done


# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl set-cursor-warp on-focus-change
riverctl focus-follows-cursor normal

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 -main-ratio 0.5 &

if [[ $(hostname) = "tymid" ]]; then 
  # App binds
  riverctl map normal Super+Shift B spawn "firefox -P gedisu --new-window https://music.youtube.com/"
  riverctl map normal Super P spawn ~/.config/river/scripts/music.sh
  riverctl map normal Super+Shift Z spawn ~/.config/river/scripts/gaming.sh

  # Moonlight rules so it always spawn in main monitor on a specific tag
  riverctl rule-add -app-id "com.moonlight_stream.Moonlight" tearing
  riverctl rule-add -app-id "com.moonlight_stream.Moonlight" tags $(( 1 << 20 ))
  riverctl rule-add -app-id "com.moonlight_stream.Moonlight" output "DP-2"

  riverctl map normal Super Comma focus-output "DP-1"
  riverctl map normal Super Period focus-output "DP-2"
  riverctl map normal Super Slash focus-output "HDMI-A-1"

  riverctl map normal Super+Shift Comma send-to-output -current-tags "DP-1"
  riverctl map normal Super+Shift Period send-to-output -current-tags "DP-2"
  riverctl map normal Super+Shift Slash send-to-output -current-tags "HDMI-A-1"
  
  wlr-randr --output "DP-1" --mode "1920x1080@144.001007"
  wlr-randr --output "DP-1" --pos 0,0
  wlr-randr --output "DP-2" --pos 1920,0
  wlr-randr --output "HDMI-A-1" --pos 4480,0
elif [[ $(hostname) = "tyoga" ]]; then
  riverctl map normal Super Comma focus-output "eDP-1"
  riverctl map normal Super Period focus-output "DP-1"

  riverctl map normal Super+Shift Comma send-to-output "eDP-1"
  riverctl map normal Super+Shift Period send-to-output "DP-1"
  riverctl input pointer-1160-4178-04881080:00_0488:1052_Touchpad tap enabled
fi
